Repository cerner/fhir.cerner.com, pull requests merged in 2023-11, with the labels that each got.

#1007 Review and Updates for Encounter
  content/millennium/dstu2/encounters/encounter.md
  content/millennium/r4/base/management/encounter.md
  lib/resources/r4/encounter.yaml
Labels: R4, DSTU2

#1001 Review and updates for Location
  content/millennium/r4/base/entities/location.md
  lib/resources/example_json/r4_examples_location.rb
Labels: R4

#1008 Review and Updates for NutritionOrder
  content/millennium/r4/clinical/care-provision/nutrition-order.md
Labels: R4

#1002 Diagnostic Report Create for Cardiology and Anatomic pathology
  content/millennium/r4/clinical/diagnostics/diagnostic-report.md
  lib/resources/example_json/r4_examples_diagnostic_report.rb
  lib/resources/r4/diagnostic_report_create.yaml
Labels: R4

#1000 Updated InsurancePlan R4 Resource
  content/millennium/r4/financial/general/insurance-plan.md
  lib/resources/example_json/r4_examples_insurance_plan.rb
Labels: R4

#1003 Updated Immunization DSTU2 Resource
  content/millennium/dstu2/medications/immunization.md
Labels: DSTU2

#1004 Updated Immunization R4 Resource
  content/millennium/r4/clinical/medications/immunization.md
  lib/resources/r4/immunization.yaml
Labels: R4
